import { sql } from 'drizzle-orm'
import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

export const almacen = sqliteTable(
  'almacen',
  {
    id: text().primaryKey().notNull(),
    nombre: text().notNull(),
    descripcion: text(),
    cantidad: integer().default(0).notNull(),
    precioCompra: real('precio_compra').notNull(),
    precioVenta: real('precio_venta').notNull(),
    minimo: integer().default(0),
    ubicacion: text(),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
    totalEntradas: integer('total_entradas').default(0),
    totalSalidas: integer('total_salidas').default(0),
    sku: text(),
    categoria: text(),
    stockActual: integer('stock_actual').default(0),
    stockReservado: integer('stock_reservado').default(0),
    stockMinimo: integer('stock_minimo').default(0),
    stockMaximo: integer('stock_maximo').default(0),
    precioCompraPromedio: real('precio_compra_promedio'),
    precioVentaPromedio: real('precio_venta_promedio'),
    fletePromedio: real('flete_promedio'),
    ventasTotales: real('ventas_totales'),
    ventasMes: real('ventas_mes'),
    ventasSemana: real('ventas_semana'),
    numeroVentas: integer('numero_ventas').default(0),
    numeroVentasMes: integer('numero_ventas_mes').default(0),
    unidadesVendidas: integer('unidades_vendidas').default(0),
    unidadesVendidasMes: integer('unidades_vendidas_mes').default(0),
    ticketPromedio: real('ticket_promedio'),
    costoTotalVendido: real('costo_total_vendido'),
    gananciaTotal: real('ganancia_total'),
    gananciaMes: real('ganancia_mes'),
    gananciaSemana: real('ganancia_semana'),
    margenBruto: real('margen_bruto'),
    margenNeto: real('margen_neto'),
    margenSobreCosto: real('margen_sobre_costo'),
    gananciaPorUnidad: real('ganancia_por_unidad'),
    contribucionTotal: real('contribucion_total'),
    rotacionInventario: real('rotacion_inventario'),
    diasInventario: integer('dias_inventario').default(0),
    velocidadVenta: real('velocidad_venta'),
    diasParaAgotarse: integer('dias_para_agotarse'),
    ultimaVenta: integer('ultima_venta'),
    diasSinVenta: integer('dias_sin_venta').default(0),
    valorStockCosto: real('valor_stock_costo'),
    valorStockVenta: real('valor_stock_venta'),
    gananciaPotencial: real('ganancia_potencial'),
    distribuidorPrincipalId: text('distribuidor_principal_id').references(() => distribuidores.id),
    numeroProveedores: integer('numero_proveedores').default(0),
    ordenesCompraActivas: integer('ordenes_compra_activas').default(0),
    scoreRentabilidad: integer('score_rentabilidad').default(50),
    scoreRotacion: integer('score_rotacion').default(50),
    scoreDemanda: integer('score_demanda').default(50),
    scoreTotal: integer('score_total').default(50),
    clasificacionAbc: text('clasificacion_abc').default('C'),
    estadoStock: text('estado_stock').default('optimo'),
    alertas: text(),
    activo: integer().default(1),
    notas: text(),
    ultimaActualizacionMetricas: text('ultima_actualizacion_metricas'),
  },
  (table) => [
    index('almacen_score_idx').on(table.scoreTotal),
    index('almacen_abc_idx').on(table.clasificacionAbc),
    index('almacen_estado_idx').on(table.estadoStock),
    index('almacen_categoria_idx').on(table.categoria),
    index('almacen_sku_idx').on(table.sku),
    index('almacen_nombre_idx').on(table.nombre),
  ],
)

export const bancos = sqliteTable(
  'bancos',
  {
    id: text().primaryKey().notNull(),
    nombre: text().notNull(),
    tipo: text().notNull(),
    capitalActual: real('capital_actual').notNull(),
    historicoIngresos: real('historico_ingresos').notNull(),
    historicoGastos: real('historico_gastos').notNull(),
    color: text().notNull(),
    icono: text(),
    orden: integer().default(0),
    activo: integer().default(1),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
    capitalMinimo: real('capital_minimo'),
    capitalMaximo: real('capital_maximo'),
    historicoTransferenciasEntrada: real('historico_transferencias_entrada'),
    historicoTransferenciasSalida: real('historico_transferencias_salida'),
    ingresosHoy: real('ingresos_hoy'),
    gastosHoy: real('gastos_hoy'),
    flujoNetoHoy: real('flujo_neto_hoy'),
    movimientosHoy: integer('movimientos_hoy').default(0),
    ingresosSemana: real('ingresos_semana'),
    gastosSemana: real('gastos_semana'),
    flujoNetoSemana: real('flujo_neto_semana'),
    movimientosSemana: integer('movimientos_semana').default(0),
    ingresosMes: real('ingresos_mes'),
    gastosMes: real('gastos_mes'),
    flujoNetoMes: real('flujo_neto_mes'),
    movimientosMes: integer('movimientos_mes').default(0),
    promedioIngresosDiario: real('promedio_ingresos_diario'),
    promedioGastosDiario: real('promedio_gastos_diario'),
    porcentajeVentas: real('porcentaje_ventas'),
    porcentajeTransferencias: real('porcentaje_transferencias'),
    porcentajeManual: real('porcentaje_manual'),
    porcentajeDistribucionGya: real('porcentaje_distribucion_gya'),
    tendenciaCapital: text('tendencia_capital').default('estable'),
    tendenciaFlujo: text('tendencia_flujo').default('neutro'),
    variacionMesAnterior: real('variacion_mes_anterior'),
    variacionSemanaAnterior: real('variacion_semana_anterior'),
    proyeccionFinMes: real('proyeccion_fin_mes'),
    diasHastaAgotamiento: integer('dias_hasta_agotamiento'),
    proyeccionTresMeses: real('proyeccion_tres_meses'),
    scoreLiquidez: integer('score_liquidez').default(50),
    scoreFlujo: integer('score_flujo').default(50),
    scoreEstabilidad: integer('score_estabilidad').default(50),
    scoreTotal: integer('score_total').default(50),
    estadoSalud: text('estado_salud').default('bueno'),
    alertas: text(),
    notas: text(),
    ultimoMovimiento: integer('ultimo_movimiento'),
    ultimaActualizacionFlujo: integer('ultima_actualizacion_flujo'),
    ultimaActualizacionMetricas: text('ultima_actualizacion_metricas'),
  },
  (table) => [
    index('banco_score_idx').on(table.scoreTotal),
    index('banco_estado_idx').on(table.estadoSalud),
    index('banco_tipo_idx').on(table.tipo),
  ],
)

export const clientes = sqliteTable(
  'clientes',
  {
    id: text().primaryKey().notNull(),
    nombre: text().notNull(),
    email: text(),
    telefono: text(),
    direccion: text(),
    rfc: text(),
    limiteCredito: real('limite_credito'),
    saldoPendiente: real('saldo_pendiente'),
    estado: text().default('activo'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
    totalCompras: real('total_compras'),
    numeroVentas: integer('numero_ventas').default(0),
    promedioCompra: real('promedio_compra'),
    ultimaCompra: integer('ultima_compra'),
    diasSinComprar: integer('dias_sin_comprar').default(0),
    totalPagado: real('total_pagado'),
    totalAbonos: real('total_abonos'),
    numeroAbonos: integer('numero_abonos').default(0),
    promedioAbono: real('promedio_abono'),
    deudaMaximaHistorica: real('deuda_maxima_historica'),
    ventasPendientes: integer('ventas_pendientes').default(0),
    creditoDisponible: real('credito_disponible'),
    porcentajeUtilizacion: real('porcentaje_utilizacion'),
    porcentajePagoPuntual: real('porcentaje_pago_puntual'),
    diasPromedioCredito: real('dias_promedio_credito'),
    frecuenciaCompra: real('frecuencia_compra'),
    gananciaGenerada: real('ganancia_generada'),
    ticketPromedio: real('ticket_promedio'),
    valorVidaCliente: real('valor_vida_cliente'),
    scoreCredito: integer('score_credito').default(50),
    scoreFrecuencia: integer('score_frecuencia').default(50),
    scoreRentabilidad: integer('score_rentabilidad').default(50),
    scoreTotal: integer('score_total').default(50),
    categoria: text().default('nuevo'),
    alertas: text(),
    notas: text(),
  },
  (table) => [
    index('cliente_score_idx').on(table.scoreTotal),
    index('cliente_categoria_idx').on(table.categoria),
    index('cliente_estado_idx').on(table.estado),
    index('cliente_nombre_idx').on(table.nombre),
  ],
)

export const distribuidores = sqliteTable(
  'distribuidores',
  {
    id: text().primaryKey().notNull(),
    nombre: text().notNull(),
    empresa: text(),
    telefono: text(),
    email: text(),
    tipoProductos: text('tipo_productos'),
    saldoPendiente: real('saldo_pendiente'),
    estado: text().default('activo'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
    direccion: text(),
    totalOrdenesCompra: real('total_ordenes_compra'),
    numeroOrdenes: integer('numero_ordenes').default(0),
    promedioOrden: real('promedio_orden'),
    ultimaOrden: integer('ultima_orden'),
    diasSinOrdenar: integer('dias_sin_ordenar').default(0),
    totalPagado: real('total_pagado'),
    numeroPagos: integer('numero_pagos').default(0),
    promedioPago: real('promedio_pago'),
    deudaMaximaHistorica: real('deuda_maxima_historica'),
    ordenesConDeuda: integer('ordenes_con_deuda').default(0),
    stockTotal: integer('stock_total').default(0),
    stockVendido: integer('stock_vendido').default(0),
    porcentajeStockVendido: real('porcentaje_stock_vendido'),
    ventasGeneradas: real('ventas_generadas'),
    gananciaGenerada: real('ganancia_generada'),
    margenPromedio: real('margen_promedio'),
    scoreCalidad: integer('score_calidad').default(50),
    scorePrecio: integer('score_precio').default(50),
    scoreRelacion: integer('score_relacion').default(50),
    scoreTotal: integer('score_total').default(50),
    categoria: text().default('nuevo'),
    confiabilidad: real(),
    tiempoPromedioEntrega: real('tiempo_promedio_entrega'),
    alertas: text(),
    notas: text(),
    porcentajePagadoPromedio: real('porcentaje_pagado_promedio'),
    diasPromedioCredito: real('dias_promedio_credito'),
    rotacionPromedio: real('rotacion_promedio'),
    velocidadVentaPromedio: real('velocidad_venta_promedio'),
    eficienciaRotacion: text('eficiencia_rotacion').default('normal'),
    roiPromedio: real('roi_promedio'),
    gananciaNetaPromedio: real('ganancia_neta_promedio'),
    scoreRotacion: integer('score_rotacion').default(50),
  },
  (table) => [
    index('distribuidor_rotacion_idx').on(table.eficienciaRotacion),
    index('distribuidor_score_idx').on(table.scoreTotal),
    index('distribuidor_categoria_idx').on(table.categoria),
    index('distribuidor_nombre_idx').on(table.nombre),
  ],
)

export const movimientos = sqliteTable(
  'movimientos',
  {
    id: text().primaryKey().notNull(),
    bancoId: text('banco_id')
      .notNull()
      .references(() => bancos.id),
    tipo: text().notNull(),
    monto: real().notNull(),
    fecha: integer().notNull(),
    concepto: text().notNull(),
    referencia: text(),
    bancoOrigenId: text('banco_origen_id').references(() => bancos.id),
    bancoDestinoId: text('banco_destino_id').references(() => bancos.id),
    clienteId: text('cliente_id').references(() => clientes.id),
    distribuidorId: text('distribuidor_id').references(() => distribuidores.id),
    ventaId: text('venta_id').references(() => ventas.id),
    ordenCompraId: text('orden_compra_id').references(() => ordenesCompra.id),
    observaciones: text(),
    createdBy: text('created_by').references(() => usuarios.id),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    categoria: text().default('Operaciones'),
  },
  (table) => [
    index('mov_referencia_idx').on(table.referencia),
    index('mov_fecha_idx').on(table.fecha),
    index('mov_tipo_idx').on(table.tipo),
    index('mov_banco_idx').on(table.bancoId),
  ],
)

export const ordenesCompra = sqliteTable(
  'ordenes_compra',
  {
    id: text().primaryKey().notNull(),
    distribuidorId: text('distribuidor_id')
      .notNull()
      .references(() => distribuidores.id),
    fecha: integer().notNull(),
    numeroOrden: text('numero_orden'),
    cantidad: integer().notNull(),
    precioUnitario: real('precio_unitario').notNull(),
    subtotal: real().notNull(),
    iva: real(),
    total: real().notNull(),
    montoPagado: real('monto_pagado'),
    montoRestante: real('monto_restante').notNull(),
    estado: text().default('pendiente'),
    bancoOrigenId: text('banco_origen_id').references(() => bancos.id),
    observaciones: text(),
    createdBy: text('created_by').references(() => usuarios.id),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
    producto: text(),
    stockActual: integer('stock_actual').default(0).notNull(),
    stockVendido: integer('stock_vendido').default(0),
    stockReservado: integer('stock_reservado').default(0),
    fleteUnitario: real('flete_unitario'),
    costoUnitarioTotal: real('costo_unitario_total'),
    fleteTotal: real('flete_total'),
    porcentajePagado: real('porcentaje_pagado'),
    numeroPagos: integer('numero_pagos').default(0),
    fechaUltimoPago: integer('fecha_ultimo_pago'),
    totalVentasGeneradas: real('total_ventas_generadas'),
    piezasVendidas: integer('piezas_vendidas').default(0),
    precioVentaPromedio: real('precio_venta_promedio'),
    numeroVentas: integer('numero_ventas').default(0),
    montoCobrado: real('monto_cobrado'),
    montoSinCobrar: real('monto_sin_cobrar'),
    porcentajeCobrado: real('porcentaje_cobrado'),
    gananciaTotal: real('ganancia_total'),
    gananciaRealizada: real('ganancia_realizada'),
    gananciaPotencial: real('ganancia_potencial'),
    margenBruto: real('margen_bruto'),
    margenSobreCosto: real('margen_sobre_costo'),
    roi: real(),
    efectivoNeto: real('efectivo_neto'),
    velocidadVenta: real('velocidad_venta'),
    diasEstimadosAgotamiento: integer('dias_estimados_agotamiento'),
    estadoStock: text('estado_stock').default('disponible'),
    estadoRentabilidad: text('estado_rentabilidad').default('sin_datos'),
    alertas: text(),
    rotacionDias: real('rotacion_dias'),
    diasDesdeCompra: integer('dias_desde_compra').default(0),
    porcentajeVendido: real('porcentaje_vendido'),
    tiempoPromedioVentaPieza: real('tiempo_promedio_venta_pieza'),
    eficienciaRotacion: text('eficiencia_rotacion').default('normal'),
    productoId: text('producto_id').references(() => almacen.id),
  },
  (table) => [
    index('oc_rentabilidad_idx').on(table.estadoRentabilidad),
    index('oc_estado_stock_idx').on(table.estadoStock),
    index('oc_estado_idx').on(table.estado),
    index('oc_fecha_idx').on(table.fecha),
    index('oc_distribuidor_idx').on(table.distribuidorId),
    uniqueIndex('ordenes_compra_numero_orden_unique').on(table.numeroOrden),
  ],
)

export const usuarios = sqliteTable(
  'usuarios',
  {
    id: text().primaryKey().notNull(),
    email: text().notNull(),
    password: text().notNull(),
    nombre: text().notNull(),
    role: text().default('viewer'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('email_idx').on(table.email),
    uniqueIndex('usuarios_email_unique').on(table.email),
  ],
)

export const ventas = sqliteTable(
  'ventas',
  {
    id: text().primaryKey().notNull(),
    clienteId: text('cliente_id')
      .notNull()
      .references(() => clientes.id),
    fecha: integer().notNull(),
    cantidad: integer().notNull(),
    precioVentaUnidad: real('precio_venta_unidad').notNull(),
    precioCompraUnidad: real('precio_compra_unidad').notNull(),
    precioFlete: real('precio_flete'),
    precioTotalVenta: real('precio_total_venta').notNull(),
    montoPagado: real('monto_pagado'),
    montoRestante: real('monto_restante').notNull(),
    montoBovedaMonte: real('monto_boveda_monte'),
    montoFletes: real('monto_fletes'),
    montoUtilidades: real('monto_utilidades'),
    estadoPago: text('estado_pago').default('pendiente'),
    observaciones: text(),
    createdBy: text('created_by').references(() => usuarios.id),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
    costoTotal: real('costo_total'),
    fleteTotal: real('flete_total'),
    porcentajePagado: real('porcentaje_pagado'),
    numeroAbonos: integer('numero_abonos').default(0),
    fechaPrimerAbono: integer('fecha_primer_abono'),
    fechaUltimoAbono: integer('fecha_ultimo_abono'),
    fechaPagoCompleto: integer('fecha_pago_completo'),
    capitalBovedaMonte: real('capital_boveda_monte'),
    capitalFletes: real('capital_fletes'),
    capitalUtilidades: real('capital_utilidades'),
    gananciaTotal: real('ganancia_total'),
    margenBruto: real('margen_bruto'),
    margenSobreCosto: real('margen_sobre_costo'),
    gananciaPorUnidad: real('ganancia_por_unidad'),
    diasDeCredito: integer('dias_de_credito').default(0),
    diasParaPago: integer('dias_para_pago'),
    esMoroso: integer('es_moroso').default(0),
    fechaVencimiento: integer('fecha_vencimiento'),
    origenLotes: text('origen_lotes'),
    numeroLotes: integer('numero_lotes').default(0),
    metodoPago: text('metodo_pago'),
    bancoDestino: text('banco_destino').references(() => bancos.id),
    alertas: text(),
    productoId: text('producto_id').references(() => almacen.id),
    ocId: text('oc_id').references(() => ordenesCompra.id),
    estado: text().default('activa'),
    precioFleteUnidad: real('precio_flete_unidad'),
    gananciaNetaVenta: real('ganancia_neta_venta'),
    margenNeto: real('margen_neto'),
  },
  (table) => [
    index('venta_moroso_idx').on(table.esMoroso),
    index('venta_estado_idx').on(table.estadoPago),
    index('venta_fecha_idx').on(table.fecha),
    index('venta_cliente_idx').on(table.clienteId),
  ],
)

export const abonos = sqliteTable(
  'abonos',
  {
    id: text().primaryKey().notNull(),
    ventaId: text('venta_id')
      .notNull()
      .references(() => ventas.id),
    clienteId: text('cliente_id')
      .notNull()
      .references(() => clientes.id),
    monto: real().notNull(),
    fecha: integer().notNull(),
    proporcion: real().notNull(),
    montoBovedaMonte: real('monto_boveda_monte'),
    montoFletes: real('monto_fletes'),
    montoUtilidades: real('monto_utilidades'),
    montoPagadoAcumulado: real('monto_pagado_acumulado').notNull(),
    montoRestantePostAbono: real('monto_restante_post_abono').notNull(),
    estadoPagoResultante: text('estado_pago_resultante').notNull(),
    concepto: text(),
    createdBy: text('created_by').references(() => usuarios.id),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('abono_fecha_idx').on(table.fecha),
    index('abono_cliente_idx').on(table.clienteId),
    index('abono_venta_idx').on(table.ventaId),
  ],
)

export const aiChatMessages = sqliteTable(
  'ai_chat_messages',
  {
    id: text().primaryKey().notNull(),
    sessionId: text('session_id').notNull(),
    userId: text('user_id'),
    role: text().notNull(),
    content: text().notNull(),
    intent: text(),
    entities: text(),
    confidence: real(),
    responseTime: integer('response_time'),
    tokensUsed: integer('tokens_used'),
    model: text(),
    metadata: text(),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('ai_chat_created_idx').on(table.createdAt),
    index('ai_chat_user_idx').on(table.userId),
    index('ai_chat_session_idx').on(table.sessionId),
  ],
)

export const aiChatSessions = sqliteTable(
  'ai_chat_sessions',
  {
    id: text().primaryKey().notNull(),
    userId: text('user_id'),
    title: text(),
    summary: text(),
    messageCount: integer('message_count').default(0),
    lastMessageAt: integer('last_message_at'),
    context: text(),
    isActive: integer('is_active').default(1),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('ai_session_active_idx').on(table.isActive),
    index('ai_session_user_idx').on(table.userId),
  ],
)

export const entradaAlmacen = sqliteTable(
  'entrada_almacen',
  {
    id: text().primaryKey().notNull(),
    ordenCompraId: text('orden_compra_id').references(() => ordenesCompra.id),
    productoId: text('producto_id').references(() => almacen.id),
    cantidad: integer().notNull(),
    costoTotal: real('costo_total').notNull(),
    fecha: integer().notNull(),
    observaciones: text(),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('entrada_fecha_idx').on(table.fecha),
    index('entrada_oc_idx').on(table.ordenCompraId),
  ],
)

export const kpisGlobales = sqliteTable(
  'kpis_globales',
  {
    id: text().primaryKey().notNull(),
    fecha: integer().notNull(),
    periodo: text().default('diario'),
    capitalTotal: real('capital_total'),
    liquidezDisponible: real('liquidez_disponible'),
    deudaClientes: real('deuda_clientes'),
    deudaDistribuidores: real('deuda_distribuidores'),
    patrimonioNeto: real('patrimonio_neto'),
    ventasDia: real('ventas_dia'),
    ventasSemana: real('ventas_semana'),
    ventasMes: real('ventas_mes'),
    ventasAnio: real('ventas_anio'),
    promedioVentaDiaria: real('promedio_venta_diaria'),
    numeroVentasDia: integer('numero_ventas_dia').default(0),
    gananciaDia: real('ganancia_dia'),
    gananciaSemana: real('ganancia_semana'),
    gananciaMes: real('ganancia_mes'),
    gananciaAnio: real('ganancia_anio'),
    margenPromedioGlobal: real('margen_promedio_global'),
    stockTotalPiezas: integer('stock_total_piezas').default(0),
    stockValorCosto: real('stock_valor_costo'),
    stockValorVenta: real('stock_valor_venta'),
    gananciaPotencialStock: real('ganancia_potencial_stock'),
    ordenesConStock: integer('ordenes_con_stock').default(0),
    rotacionInventario: real('rotacion_inventario'),
    diasInventario: integer('dias_inventario').default(0),
    porcentajeCobranza: real('porcentaje_cobranza'),
    puntualidadPagos: real('puntualidad_pagos'),
    clientesActivos: integer('clientes_activos').default(0),
    clientesNuevos: integer('clientes_nuevos').default(0),
    clientesMorosos: integer('clientes_morosos').default(0),
    clientesVip: integer('clientes_vip').default(0),
    tendenciaVentas: text('tendencia_ventas').default('estable'),
    tendenciaGanancias: text('tendencia_ganancias').default('estable'),
    tendenciaLiquidez: text('tendencia_liquidez').default('estable'),
    indiceSaludFinanciera: integer('indice_salud_financiera').default(50),
    riesgoLiquidez: text('riesgo_liquidez').default('medio'),
    riesgoCredito: text('riesgo_credito').default('medio'),
    alertasCriticas: integer('alertas_criticas').default(0),
    alertasAdvertencia: integer('alertas_advertencia').default(0),
    alertasInfo: integer('alertas_info').default(0),
    alertasJson: text('alertas_json'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [index('kpis_periodo_idx').on(table.periodo), index('kpis_fecha_idx').on(table.fecha)],
)

export const pagosDistribuidor = sqliteTable(
  'pagos_distribuidor',
  {
    id: text().primaryKey().notNull(),
    ordenCompraId: text('orden_compra_id')
      .notNull()
      .references(() => ordenesCompra.id),
    distribuidorId: text('distribuidor_id')
      .notNull()
      .references(() => distribuidores.id),
    bancoOrigenId: text('banco_origen_id')
      .notNull()
      .references(() => bancos.id),
    monto: real().notNull(),
    fecha: integer().notNull(),
    montoPagadoAcumulado: real('monto_pagado_acumulado').notNull(),
    montoRestantePostPago: real('monto_restante_post_pago').notNull(),
    estadoPagoResultante: text('estado_pago_resultante').notNull(),
    concepto: text(),
    referencia: text(),
    createdBy: text('created_by').references(() => usuarios.id),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('pago_dist_fecha_idx').on(table.fecha),
    index('pago_dist_distribuidor_idx').on(table.distribuidorId),
    index('pago_dist_oc_idx').on(table.ordenCompraId),
  ],
)

export const salidaAlmacen = sqliteTable(
  'salida_almacen',
  {
    id: text().primaryKey().notNull(),
    ventaId: text('venta_id').references(() => ventas.id),
    productoId: text('producto_id').references(() => almacen.id),
    cantidad: integer().notNull(),
    origenLotes: text('origen_lotes'),
    fecha: integer().notNull(),
    observaciones: text(),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('salida_fecha_idx').on(table.fecha),
    index('salida_venta_idx').on(table.ventaId),
  ],
)

export const alertas = sqliteTable(
  'alertas',
  {
    id: text().primaryKey().notNull(),
    tipo: text().notNull(),
    severidad: text().default('info').notNull(),
    estado: text().default('activa').notNull(),
    titulo: text().notNull(),
    descripcion: text().notNull(),
    entidadTipo: text('entidad_tipo'),
    entidadId: text('entidad_id'),
    entidadNombre: text('entidad_nombre'),
    valorActual: real('valor_actual'),
    valorUmbral: real('valor_umbral'),
    unidad: text(),
    accionSugerida: text('accion_sugerida'),
    urlAccion: text('url_accion'),
    metadata: text(),
    fechaCreacion: integer('fecha_creacion').default(sql`(unixepoch())`),
    fechaVista: integer('fecha_vista'),
    fechaResuelta: integer('fecha_resuelta'),
    fechaExpiracion: integer('fecha_expiracion'),
    resueltaPor: text('resuelta_por').references(() => usuarios.id),
    notasResolucion: text('notas_resolucion'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('alerta_fecha_idx').on(table.fechaCreacion),
    index('alerta_entidad_idx').on(table.entidadTipo, table.entidadId),
    index('alerta_estado_idx').on(table.estado),
    index('alerta_severidad_idx').on(table.severidad),
    index('alerta_tipo_idx').on(table.tipo),
  ],
)

export const alertasConfig = sqliteTable(
  'alertas_config',
  {
    id: text().primaryKey().notNull(),
    tipo: text().notNull(),
    activo: integer().default(1),
    umbral: real().notNull(),
    severidad: text().default('advertencia').notNull(),
    frecuenciaHoras: integer('frecuencia_horas').default(24),
    ultimaVerificacion: integer('ultima_verificacion'),
    notificarEmail: integer('notificar_email').default(0),
    notificarPush: integer('notificar_push').default(1),
    emailsDestino: text('emails_destino'),
    descripcionPersonalizada: text('descripcion_personalizada'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
  },
  (table) => [uniqueIndex('alertas_config_tipo_unique').on(table.tipo)],
)

export const auditLog = sqliteTable(
  'audit_log',
  {
    id: text().primaryKey().notNull(),
    userId: text('user_id').references(() => usuarios.id),
    userEmail: text('user_email'),
    userRole: text('user_role'),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    sessionId: text('session_id'),
    accion: text().notNull(),
    entidadTipo: text('entidad_tipo').notNull(),
    entidadId: text('entidad_id'),
    entidadNombre: text('entidad_nombre'),
    valorAnterior: text('valor_anterior'),
    valorNuevo: text('valor_nuevo'),
    camposModificados: text('campos_modificados'),
    modulo: text(),
    origen: text().default('web'),
    descripcion: text(),
    montoInvolucrado: real('monto_involucrado'),
    bancosAfectados: text('bancos_afectados'),
    exito: integer().default(1).notNull(),
    errorMensaje: text('error_mensaje'),
    errorStack: text('error_stack'),
    timestamp: integer()
      .default(sql`(unixepoch())`)
      .notNull(),
  },
  (table) => [
    index('audit_session_idx').on(table.sessionId),
    index('audit_timestamp_idx').on(table.timestamp),
    index('audit_entidad_idx').on(table.entidadTipo, table.entidadId),
    index('audit_accion_idx').on(table.accion),
    index('audit_user_idx').on(table.userId),
  ],
)

export const conciliaciones = sqliteTable(
  'conciliaciones',
  {
    id: text().primaryKey().notNull(),
    bancoId: text('banco_id')
      .notNull()
      .references(() => bancos.id),
    periodo: text().notNull(),
    fechaInicio: integer('fecha_inicio').notNull(),
    fechaFin: integer('fecha_fin').notNull(),
    estado: text().default('pendiente').notNull(),
    saldoSistema: real('saldo_sistema').notNull(),
    saldoExtracto: real('saldo_extracto').notNull(),
    diferencia: real().notNull(),
    diferenciaPorcentaje: real('diferencia_porcentaje').notNull(),
    movimientosSistema: integer('movimientos_sistema').default(0),
    movimientosExtracto: integer('movimientos_extracto').default(0),
    movimientosConciliados: integer('movimientos_conciliados').default(0),
    movimientosPendientes: integer('movimientos_pendientes').default(0),
    partidasPendientesJson: text('partidas_pendientes_json'),
    observaciones: text(),
    conciliadoPor: text('conciliado_por').references(() => usuarios.id),
    fechaConciliacion: integer('fecha_conciliacion'),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('conciliacion_estado_idx').on(table.estado),
    index('conciliacion_periodo_idx').on(table.periodo),
    index('conciliacion_banco_idx').on(table.bancoId),
  ],
)

export const devoluciones = sqliteTable(
  'devoluciones',
  {
    id: text().primaryKey().notNull(),
    ventaId: text('venta_id')
      .notNull()
      .references(() => ventas.id),
    clienteId: text('cliente_id')
      .notNull()
      .references(() => clientes.id),
    tipo: text().notNull(),
    motivo: text().notNull(),
    estado: text().default('pendiente').notNull(),
    cantidadOriginal: integer('cantidad_original').notNull(),
    cantidadDevuelta: integer('cantidad_devuelta').notNull(),
    precioVentaUnidad: real('precio_venta_unidad').notNull(),
    precioCompraUnidad: real('precio_compra_unidad').notNull(),
    precioFleteUnidad: real('precio_flete_unidad').notNull(),
    montoTotalDevolucion: real('monto_total_devolucion').notNull(),
    reversionBovedaMonte: real('reversion_boveda_monte').notNull(),
    reversionFletes: real('reversion_fletes').notNull(),
    reversionUtilidades: real('reversion_utilidades').notNull(),
    montoReembolso: real('monto_reembolso'),
    estadoReembolso: text('estado_reembolso').default('no_aplica'),
    bancoReembolso: text('banco_reembolso').references(() => bancos.id),
    devolverStock: integer('devolver_stock').default(1),
    ocDestinoId: text('oc_destino_id').references(() => ordenesCompra.id),
    stockDevuelto: integer('stock_devuelto').default(0),
    aprobadoPor: text('aprobado_por').references(() => usuarios.id),
    fechaAprobacion: integer('fecha_aprobacion'),
    procesadoPor: text('procesado_por').references(() => usuarios.id),
    fechaProcesamiento: integer('fecha_procesamiento'),
    observaciones: text(),
    motivoRechazo: text('motivo_rechazo'),
    createdBy: text('created_by').references(() => usuarios.id),
    createdAt: integer('created_at').default(sql`(unixepoch())`),
    updatedAt: integer('updated_at').default(sql`(unixepoch())`),
  },
  (table) => [
    index('devolucion_fecha_idx').on(table.createdAt),
    index('devolucion_estado_idx').on(table.estado),
    index('devolucion_cliente_idx').on(table.clienteId),
    index('devolucion_venta_idx').on(table.ventaId),
  ],
)
